/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
    api("org.bouncycastle:bcprov-jdk18on:1.77")
    // https://mvnrepository.com/artifact/com.klinec/jcardsim
    api("com.klinec:jcardsim:3.0.5.11")
    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    api("commons-cli:commons-cli:1.6.0")
    // https://mvnrepository.com/artifact/org.yaml/snakeyaml
    api("org.yaml:snakeyaml:1.19")
}