/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
    api("org.bouncycastle:bcprov-jdk18on:1.77")
    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    // We need 1.5.0, as for some reason 1.6.0 doesn't work (arguments don't ger parsed properly).
    api("commons-cli:commons-cli:1.5.0")
    // https://mvnrepository.com/artifact/org.yaml/snakeyaml
    api("org.yaml:snakeyaml:2.2")
    // https://mvnrepository.com/artifact/com.klinec/jcardsim
    api("com.klinec:jcardsim:3.0.5.11")

    testImplementation(platform("org.junit:junit-bom:5.11.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit-pioneer:junit-pioneer:2.3.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    sourceCompatibility = JavaVersion.VERSION_15
}